[phases.setup]
nixPkgs = ["nodejs"]
nixLibs = []

[phases.install]
cmds = [
  "npm install",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npm install",
  "npx prisma generate"
]

[start]
cmd = "npx tsx bot/index.ts"
