// Design tokens for AI Estimate v2 — light theme
export const T = {
  background: "#F8FAFC",
  panel: "#FFFFFF",
  panelElevated: "#F1F5F9",
  panelSoft: "#F8FAFC",
  borderSoft: "#E2E8F0",
  borderStrong: "#CBD5E1",
  borderAccent: "#3B5BFF",
  textPrimary: "#0F172A",
  textSecondary: "#475569",
  textMuted: "#94A3B8",
  accentPrimary: "#3B5BFF",
  accentPrimarySoft: "#EEF2FF",
  accentSecondary: "#7C5CFF",
  accentSecondarySoft: "#F5F3FF",
  success: "#16A34A",
  successSoft: "#F0FDF4",
  warning: "#EA580C",
  warningSoft: "#FFF7ED",
  danger: "#DC2626",
  dangerSoft: "#FEF2F2",
  // Extended palette for colorful cards & accents
  teal: "#0D9488",
  tealSoft: "#F0FDFA",
  indigo: "#4F46E5",
  indigoSoft: "#EEF2FF",
  amber: "#D97706",
  amberSoft: "#FFFBEB",
  rose: "#E11D48",
  roseSoft: "#FFF1F2",
  sky: "#0284C7",
  skySoft: "#F0F9FF",
  emerald: "#059669",
  emeraldSoft: "#ECFDF5",
  violet: "#7C3AED",
  violetSoft: "#F5F3FF",
} as const;
